# Generated by Django 5.1 on 2025-04-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_premiumuser',
            field=models.BooleanField(default=False),
        ),
    ]
