# Generated by Django 5.1 on 2025-05-05 21:55

import django.utils.timezone
import imghostapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imghostapp', '0002_image_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=imghostapp.models.user_directory_path),
        ),
    ]
